account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)
app_name = "account"

urlpatterns = [
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from .views import SearchView
from myblog import views
from django.contrib.auth.views import LoginView
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('search/', SearchView.as_view(), name='search'), 
    path('accounts/login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/signup/', views.SignUpView.as_view(), name="signup"),
    path('account/', include('account.urls')),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

posts/urls.py
from django.urls import path
from django.conf.urls import url
from .import views
# from posts.views import HomeView
from posts.views import HomeView

app_name = 'posts'
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r"^$", views.AllPosts.as_view(), name="all"),
    path('<slug><int:pk>.', views.detail, name='detail'),
    url(
        r"by/(?P<username>[-\w]+)/$",
        views.UserPosts.as_view(),
        name="for_user"
    ),
    url(
        r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.SinglePost.as_view(),
        name="single"
    ),
     url(r'^user/(\w+)/$', views.profile, name='profile'),
         url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),

]    

account/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

posts/models.py
from django.db import models
from django.conf import settings
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from django.utils.translation import pgettext_lazy
# Create your models here.
from django.contrib.auth.models import User
import misaka


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="posts")
    users = models.ManyToManyField(User)
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=120)
    title_html = models.TextField(editable=False)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False,auto_now_add=False,)
    slug = models.SlugField(unique=True)
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title_html = misaka.html(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

class Profile(models.Model):
    
    first_name = models.CharField(max_length=50, db_column='first_name')
    last_name = models.CharField(max_length=50, db_column='last_name')


class UsersProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    def __str__(self):
        return self.user.username

posts/forms.py
from django import forms
from .models import Post
from django.contrib.admin import widgets

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'draft', 'publish', 'slug']

class LoginForm(forms.Form):
    username = forms.CharField(label='User Name', max_length=64)
    password = forms.CharField(widget=forms.PasswordInput())


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))

    class Meta:
        model = Post
        fields = ('title',)

account/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User


def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

myblog/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView
from django.views import View
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from posts.models import Post
class SearchView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get("q")
        qs = None
        if query:
            qs = Post.objects.filter(
                    Q(title__icontains=query)
                )
        context = {"posts": qs}
        return render(request, "search.html", context)

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.forms import PostForm
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, render
from braces.views import SelectRelatedMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from posts import forms

from .models import Post


class AllPosts(ListView):
    model = Post
    paginate_by = 3
    template_name = 'posts/post_list.html'
    def get(self, request):
        posts = Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        args = {
            'posts': posts, 'users': users
        }
        return render(request, self.template_name, args)
    

def detail(request, slug, pk):
    post = get_object_or_404(Post, slug=slug, pk=pk)
    return render(request, 'posts/detail.html', {'post': post})


class UserPosts(ListView):
    model = Post
    template_name = "posts/user_timeline.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class SinglePost(DetailView):
    model = Post


    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

def profile(request, username):
    user = get_object_or_404(User.objects, username=username)
    posts = Post.objects.filter(user=user)
    return render(request, 'posts/profile.html', {'username':username,'posts': posts})





def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'home/profile.html', args)


class HomeView(TemplateView):
    template_name = 'posts/post_list.html'

    def get(self, request):
        posts = Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        

        args = {
            'posts': posts, 'users': users
        }
        return render(request, self.template_name, args)

    

account/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

account/templates/accounts/profile.html
{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    
</div>

{% endblock %}

posts/templates/posts/_post.html
{% load humanize %}
{% load static from staticfiles %}
		
		<!-- {{ post.title_html|safe }} </h2> -->
	
		
 <div class="col s12 m4">
   <div class="card">
 <div class="card-image">
            
        <h5>
           <a href="{% url 'posts:detail' post.slug post.pk %}">
			 {{ post.title }} </a>
        </h5>
   

        
 </div>
<div class="card-content">
            <p> {{ post.content|slice:"100" }}<a href="{% url 'posts:detail' post.slug post.pk %}"> Read More </a></p> 
</div>
 <div class="card-action">
 	<div class="col s5">
<a href="{% url 'account:view_profile_with_pk' pk=post.user.pk %}">
                {{ post.user }} 
            </a>
 
</div>

        	<div class="col s7">
          <time class="time"><a href="{%url 'posts:detail' post.slug post.pk  %}">{{ post.publish }}</a></time>
        </div>


</div>
</div></div>

posts/templates/posts/detail.html
{% extends "posts/layout.html" %}
{% load humanize %}
{% load static from staticfiles %}


{% block post_content %}
		</h2>
		<!-- {{ post.title_html|safe }} </h2> -->
		<h1> {{ post.title }} </h1>
		

		{% endblock %}
	</div>
</div>

posts/templates/posts/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title> {% block title %} {% endblock %} </title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

</head>
<body> 
	  <nav class="light-blue lighten-1" role="navigation">
    <div class="container">
    <div class="row">
  <div class="col s2">
    
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'posts:all' %}" class="brand-logo">My App</a>

    </div></div>

      <div class="col s6">
         {% include "search_form.html" %} 
    
       </div>
   
         
         <div class="col s4">
    
      <ul class="right hide-on-med-and-down">
       {% if user.is_authenticated %}
        <li>  <a class="navbar-text navbar-right" href="{% url 'posts:profile' user.username %}">{{ user.username }}</a> </li>
        

        	<li><a href="{% url 'logout' %}"> Logout </a></li>        	
       {% else %}
       		<li> <a href="{% url 'login' %}">Log in </a></li>
           <li> <a href="{% url 'signup' %}">Sign Up </a></li>
         
          
          
       {% endif %}
      </ul>

      <ul id="nav-mobile" class="side-nav">
       {% if user.is_authenticated %}
        	<li><a href="#">:{{user}}</a></li>

     
        	<li><a href="{% url 'logout' %}?next=/"> Logout </a></li>
        	
       {% else %}
       		<li> <a href="/login/?next=/">Log in </a></li>
            <li> <a href="signup">Sign Up </a></li>
       {% endif %}
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </li>
</ul>
</div>
  </nav>




<div class="posts-page">
	<div class="container">
		<div class="row">
		
			{% block post_content %}{% endblock %}

			
		</div>
	</div>
</div>

 {% block footer %}
<footer class="light-blue lighten-1" role="navigation">
<div class="footer-copyright">
      <div class="container">
        <div class="row center">
      Made by <span class="#f57f17 yellow darken-4">   Tanveer Ahmed  </span>
      <p>  <a href="https://github.com/tanveerahmad1517/"> GitHub: </a> </p>
      <p>  <a href="https://www.facebook.com/tanveerahmadst"> Facebook: </a> </p>
      </div>
    </div>
  </div>
</footer>
{% endblock footer %}

<!--  Scripts-->
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>
   <script src="{% static 'js/drop.js' %}"></script>
 

    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block javascript %}{% endblock %}
</body>
</html>

posts/templates/posts/post_list.html
{% extends "posts/layout.html" %}


</div>
{% block post_content %}
</div>
<div class="row">

	{% for post in posts %}
		{% include "posts/_post.html" %}

{% if forloop.counter|divisibleby:3 and not forloop.last %}
        </div><br><div class="row">
      {% endif %}
    

	{% endfor %}

</div>

<ul class="pagination">
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="waves-effect"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>

    {% else %}
      <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active">{{ i }} </li>
      {% else %}
        <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
     
    {% else %}
      <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/search.html
{% extends "posts/layout.html" %}
{% block post_content %}
    {% if request.GET.q %}
        <p class='lead'>Results for <b> {{ request.GET.q }} </b> </p>
       <hr/>
    {% endif %}
   
        <h1>Posts</h1>
           <hr/>
    {% for post in posts %}
        <h5> <a href="{% url 'posts:detail' post.slug post.pk %}"> {{post.title}} </a> 
        </h5>
    {% empty %}
        <p>No users found</p>
    {% endfor %}
     
{% endblock %}

templates/search_form.html
 <form id='navbar-search-form' class="navbar-form navbar-left" method='GET' action='{% url "search" %}'>
        <div class="form-group">
            <input class="form-control" type='text' name='q' placeholder='Your search' value='{{ request.GET.q }}'/>
            </div>
        <input class="btn btn-default" type='submit' value='Search'/>

</form>